tableEle = document.createElement('table');
tableEle.border = "1px solid";
  tr1=document.createElement('tr');
  trd11=document.createElement('td');
  trd11.textContent ='name';
  trd12=document.createElement('td');
  trd12.textContent ='age';
  trd13=document.createElement('td');
  trd13.textContent ='address';
  trd14=document.createElement('td');
  trd14.textContent ='DOB';
  trd15=document.createElement('td');
  trd15.textContent ='email';
  trd16=document.createElement('td');
  trd16.textContent ='gender';
  tr1.appendChild(trd11);
  tr1.appendChild(trd12);
  tr1.appendChild(trd13);
  tr1.appendChild(trd14);
  tr1.appendChild(trd15);
  tr1.appendChild(trd16);

  tr2=document.createElement('tr');
  trd21=document.createElement('td');
  trd21.textContent ='john';
  trd22=document.createElement('td');
  trd22.textContent ='20';
  trd23=document.createElement('td');
  trd23.textContent ='mysore';
  trd24=document.createElement('td');
  trd24.textContent ='22-may-1997';
  trd25=document.createElement('td');
  trd25.textContent ='john@gmail.com';
  trd26=document.createElement('td');
  trd26.textContent ='male';
  tr2.appendChild(trd21);
  tr2.appendChild(trd22);
  tr2.appendChild(trd23);
  tr2.appendChild(trd24);
  tr2.appendChild(trd25);
  tr2.appendChild(trd26);

  tr3=document.createElement('tr');
  trd31=document.createElement('td');
  trd31.textContent ='daniel';
  trd32=document.createElement('td');
  trd32.textContent ='25';
  trd33=document.createElement('td');
  trd33.textContent ='mysore';
  trd34=document.createElement('td');
  trd34.textContent ='20-aug-1994';
  trd35=document.createElement('td');
  trd35.textContent ='dan@gmail.com';
  trd36=document.createElement('td');
  trd36.textContent ='male';
  tr3.appendChild(trd31);
  tr3.appendChild(trd32);
  tr3.appendChild(trd33);
  tr3.appendChild(trd34);
  tr3.appendChild(trd35);
  tr3.appendChild(trd36);

  tr4=document.createElement('tr');
  trd41=document.createElement('td');
  trd41.textContent ='sany';
  trd42=document.createElement('td');
  trd42.textContent ='26';
  trd43=document.createElement('td');
  trd43.textContent ='banglore';
  trd44=document.createElement('td');
  trd44.textContent ='2-dec-1993';
  trd45=document.createElement('td');
  trd45.textContent ='san@gmail.com';
  trd46=document.createElement('td');
  trd46.textContent ='female';
  tr4.appendChild(trd41);
  tr4.appendChild(trd42);
  tr4.appendChild(trd43);
  tr4.appendChild(trd44);
  tr4.appendChild(trd45);
  tr4.appendChild(trd46);

 
 
  
  let t=tableEle.appendChild(tr1);
  console.log(t);
  let t1=tableEle.appendChild(tr2);
  console.log(t1);
  let t2=tableEle.appendChild(tr3);
  console.log(t2);
  let t3=tableEle.appendChild(tr4);
  console.log(t3);
document.body.appendChild(tableEle);
